---
title: "Swing State Votes"
author: "Nyderia Hall & Margaret Szlosek"
output:
  html_document:
    code folding: hide
---
```{r}
library(tidyverse)
library(RColorBrewer)
library(ggthemes)

```

```{r}

states <- c("FL", "PA", "OH") #chosen as they are swing states


parties <- c("D", "R") #filtering by major parties

houseelection <- house_elections %>% #creating a copy of house_elections
 filter(state == states) %>% #filtering by swing states name above
  filter(party==parties) %>% #filtering by major parties
 rename(cand_id = fec_id) #the ids of candidates appear in both tables, but under different names, so one is being renamed

candi <- candidates %>% #creating copy of candidates
 rename(state = cand_office_state) %>% #the lables for states are different for the two data sets, so they must be renamed so they can merge properly
 filter(state == states) #filter by states above

elections2 <- full_join(houseelection, candi, by = "cand_id")

ggplot(data = elections2, aes(x = general_votes, y = primary_votes,  colour = party)) +
  geom_text(aes(label=ge_winner)) +
  scale_colour_manual(values=c("D"="royalblue", "R"="firebrick2")) +
  ggtitle("Election Votes in Swing States ") +
  labs(x = "General Election Votes (1000s)") +
  labs (y = "Primary Election Votes (1000s)") +
  scale_x_continuous(breaks=c(50000, 100000, 150000, 200000, 250000), labels = c("50", "100", "150", "200", "250")) +
  scale_y_continuous(breaks=c(20000, 40000, 60000, 80000), labels = c("20,", "40", "60", "80")) +
  theme_economist()


```

